name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: code_quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Setup python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.9
    - name: Setup rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: Set up pre-commit cache
      uses: actions/cache@v3.0.11
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-precommit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: ${{ runner.os }}-precommit-
    - uses: pre-commit/action@v3.0.0
