name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  solve_puzzles:
    name: Solve puzzles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
        puzzle-year: ['2015', '2016', '2017', '2018', '2019', '2020']
    steps:
    - uses: actions/checkout@v2.3.5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Set up Poetry cache for Python dependencies
      uses: actions/cache@v2.1.6
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install Poetry
      uses: snok/install-poetry@v1.2.1
    - name: Install dependencies
      run: poetry install --no-interaction
    - name: Solve puzzles of year ${{ matrix.puzzle-year }}
      run: poetry run pytest -k "test_correctly_solve_puzzle[${{ matrix.puzzle-year }}-"
